### ISSUE TITLE
Consider using LGPL instead of GPL

### ISSUE THREAD

**Issue by LizAinslie** [isXander/UltralightFabric#6]
Hey!

I've been tasked with some work regarding Ultralight in Fabric and this library would be very useful to me. Unfortunately I can't use it as my company isn't interested in open-sourcing our software (this is not my decision, and not one I can influence given my position is an independent contractor) and it is licensed under the GPL 3.0 which doesn't allow this.

You could change it to LGPL (which respects the original license source on the repo you adapted it from) and we could use this instead of spending a few days implementing Ultralight. It's also company policy to credit open source libraries we use in our end-user application so you'd receive due credit for your contribution.

If you'd like to talk further I'd be glad to talk on Discord. My tag is `RailRunner16#0016`. I'd appreciate to hear from you.

**Comment by leumasme** [comment]
The original repo is GPL; downgrading from GPL to LGPL is not possible without the permission of all contributors.

**Comment by LizAinslie** [comment]
Oh, I see. Missed that, thanks! _Guess I'm writing this implementation by hand haha_

**Comment by leumasme** [comment]
@isXander should also fix the readme as it still says the unlicense

**Comment by isXander** [comment]
Sorry about the license, @LizAinslie I will change it now.

**Comment by leumasme** [comment]
@isXander ?? did you read what i said? this is against liquidbounce's license.

**Comment by LizAinslie** [comment]
Yeah, considering what @leumasme mentioned unless you ask the LiquidBounce authors, I can't use it anyway. It might be something you can do later but as of right now I have a deadline I must meet. However, I will look at this repo for an example implementation as it seems to have what I need. (I've been looking off and on already but was hesitant)
